image: ubuntu:focal

variables:
  ANDROID_HOME:             "$PWD/android-sdk"
  ANDROID_SDK_TOOLS:        "7583922_latest"
  ANDROID_SDK_LICENSE_HASH: "24333f8a63b6825ea9c5514f83c2829b004d1fee"

before_script:
  - apt-get update
  - apt-get -y upgrade
  - apt-get -y install ${JDK_PACKAGE}
  - apt-get -y install wget gradle
  - wget --quiet --output-document=commandlinetools-linux.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}.zip
  - mkdir -p ${ANDROID_HOME}
  - unzip -d ${ANDROID_HOME} commandlinetools-linux.zip
  - mkdir -p ${ANDROID_HOME}/licenses
  - echo -e "\n${ANDROID_SDK_LICENSE_HASH}" >> ${ANDROID_HOME}/licenses/android-sdk-license

build:
  parallel:
    matrix:
      - JDK_PACKAGE: [ openjdk-8-jdk, openjdk-11-jdk ]
  script:
    - gradle build --stacktrace
